### ISSUE TITLE
Question: How to mc admin policy create using the sdk?

### ISSUE THREAD

**Issue by rajan123456** [minio/madmin-go#209]
Hi,

I am trying to create a new policy using the sdk, but I only cannot find the API method for it. Please help. Thanks.

https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-policy-create.html#command-mc.admin.policy.create

**Comment by klauspost** [comment]
You can follow the [tail in mc](https://github.com/minio/mc/blob/5f39522e69025bea6be0d350b65fdec2de2785c8/cmd/admin-policy-create.go#L120)

It is an admin API, so not in this repo, but: https://github.com/minio/madmin-go/blob/main/policy-commands.go#L171
