### ISSUE TITLE
Backward compatibility for ServiceStop

### ISSUE THREAD

**Issue by roosterfish** [minio/madmin-go#266]
Hi,

One of the recent [commits](https://github.com/minio/madmin-go/commit/46040c00d75e35b325cca832b9cf82621c815905) removed the `ServiceStop` function.

Was this intentional or can it be moved back in?
[This](https://github.com/minio/madmin-go/commit/66fab65f959fd329672666b7ad8a39f1551df3a7#diff-5422f298949471cc1858985b8cf917fe0026f7bc14e58fba05ae3e4a35452f75L38) commit added the option to be able to call the new V2 endpoint using the old `ServiceStop` instead of `ServiceStopV2` which looks reasonable to me.

Thanks!

**Comment by vadmeste** [comment]
@roosterfish could you clarify if you are facing any issues ? if yes, what is it ?

**Comment by roosterfish** [comment]
@vadmeste In LXD we currently use version `v1.7.5` of `madmin-go`. Up until now we just called `ServiceStop`, but since one of the last [releases](https://github.com/minio/minio/releases/tag/RELEASE.2024-01-28T22-35-53Z) the API returns an error explaining you should use the V2 instead: `process actions are not supported via this API anymore, please upgrade 'mc' or madmin-go to use ServiceV2() API`.

By checking the commit history it looks backward compatibility was recently added but removed again in https://github.com/minio/madmin-go/commit/46040c00d75e35b325cca832b9cf82621c815905 three days ago.

**Comment by harshavardhana** [comment]
I can add it back

**Comment by harshavardhana** [comment]
Fixed f4fd6f66c63d25fe68c9dd10a66bf704cd75bfd8
