### ISSUE TITLE
`AddGroup` and `DeleteGroup` group management functions missing

### ISSUE THREAD

**Issue by ijsf** [minio/madmin-go#273]
It seems that the functionality for adding and removing groups is missing, despite functions for group member management and status being present. I would expect something like `AddGroup` and `RemoveGroup` to be present, since the CLI also provides these options.

**Comment by donatello** [comment]
As documented at https://github.com/minio/madmin-go/blob/v1.7.5/group-commands.go#L39 :

```
UpdateGroupMembers - adds/removes users to/from a group. Server creates the group as needed. Group is removed if remove request is made on empty group. 
```

There is no explicit add a group command (to create an "empty" group) - I don't believe we need it. The same API performs group removal if a remove request with no members is done on an empty group.

**Comment by ijsf** [comment]
Got it thanks, it wasn't 100% obvious from the docs (and function name) that this would be a side effect of that particular function.
