### ISSUE TITLE
A bug of Speedtest API

### ISSUE THREAD

**Issue by BaiJing-LR** [minio/madmin-go#29]
When I use the Speedtest API to test, return a error: 
This is my test code:
```
	res,err:=mdmClnt.Speedtest(context.Background(),madmin.SpeedtestOpts{
		Size:        102400,
		Concurrency: 0,
		Duration:    10*time.Second,
		Autotune:    true,
	})
```
`err: json: cannot unmarshal array into Go value of type madmin.SpeedTestResult`

**Comment by harshavardhana** [comment]
You need to use latest master @BaiJing-LR
