### ISSUE TITLE
Dependency loop with github.com/minio/pkg

### ISSUE THREAD

**Issue by gibmat** [minio/madmin-go#324]
#312 introduced a dependency loop with github.com/minio/pkg, which in turns depends on this library. Cyclic dependencies can cause headaches and makes packaging for distros such as Debian more difficult.

**Comment by harshavardhana** [comment]
What cyclic dependency?

**Comment by klauspost** [comment]
Debian should fix their stuff. There is no formal cyclic dependency.

That said "internal" stuff should be removed from the structs:

https://github.com/minio/madmin-go/pull/312/files#diff-95137664ccb466a02328b0edbdb1ec3ab2e8ada6863f13955a58e28ea7e8152bR47 and https://github.com/minio/madmin-go/pull/312/files#diff-95137664ccb466a02328b0edbdb1ec3ab2e8ada6863f13955a58e28ea7e8152bR37

... doesn't really belong as neither can be serialized.

Also, there are msgpack fields, but no generated serializer, so not sure what the intent is.

@SSushmitha8 Maybe a second pass would be appropriate.

**Comment by harshavardhana** [comment]
the only dependency on pkg was for pkg/v3/xtime @klauspost and I moved that to madmin-go itself and this chapter can be closed

8898ee1c935e107665657be3ca5c2118a4c21329

**Comment by SSushmitha8** [comment]
@klauspost @gibmat  This structs were introduced to make both aistor and minio can point to the same structs and it would be easy to monitor and fix if there is any change in these structs

**Comment by klauspost** [comment]
@SSushmitha8 Yeah. It more that abstraction is leaking.

`Clnt *miniogo.Core` and `Ctx context.Context` seems like they don't really belong, since they cannot be transferred.

I guess if things compile the msgp serializer isn't needed for these.

Minor things, though.
