### ISSUE TITLE
Memory Issues with ListUsers

### ISSUE THREAD

**Issue by robbertvdg** [minio/madmin-go#41]
Hi,

I saw a high memory consumption in our go application that uses the minio admin sdk. I tracked it down to the [ListUsers](https://github.com/minio/madmin-go/blob/b4edc0a9f66b120b73cbb6cafdbc93ff3beb1d8a/user-commands.go#L155) function. It seems the results are not properly garbage collected with multiple calls.

Here is a code snippet and the memory consumption:

```go
ctx := context.Background()
for i := 1; i <= 10; i++ {
    PrintMemUsage()
    _, err := r.MinioAdminClient.ListUsers(ctx)
    if err != nil {
	return nil, err
    }
}
```
Memory usages:
Alloc = 99 MiB  TotalAlloc = 123 MiB    Sys = 139 MiB   NumGC = 9
Alloc = 92 MiB  TotalAlloc = 189 MiB    Sys = 206 MiB   NumGC = 10
Alloc = 156 MiB TotalAlloc = 253 MiB    Sys = 206 MiB   NumGC = 10
Alloc = 156 MiB TotalAlloc = 253 MiB    Sys = 206 MiB   NumGC = 10
Alloc = 156 MiB TotalAlloc = 253 MiB    Sys = 206 MiB   NumGC = 10
Alloc = 220 MiB TotalAlloc = 317 MiB    Sys = 272 MiB   NumGC = 11
Alloc = 220 MiB TotalAlloc = 318 MiB    Sys = 272 MiB   NumGC = 11
Alloc = 284 MiB TotalAlloc = 382 MiB    Sys = 338 MiB   NumGC = 11
Alloc = 284 MiB TotalAlloc = 382 MiB    Sys = 338 MiB   NumGC = 11
Alloc = 284 MiB TotalAlloc = 382 MiB    Sys = 338 MiB   NumGC = 11

Can this be investigated?

**Comment by klauspost** [comment]
Looking at the function, there is nothing there that can really be an issue.

**Comment by robbertvdg** [comment]
The function: 
```go
func PrintMemUsage() {
	var m run.MemStats
	run.ReadMemStats(&m)
	// For info on each, see: https://golang.org/pkg/runtime/#MemStats
	fmt.Printf("Alloc = %v MiB", bToMb(m.Alloc))
	fmt.Printf("\tTotalAlloc = %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\tSys = %v MiB", bToMb(m.Sys))
	fmt.Printf("\tNumGC = %v\n", m.NumGC)
}
```

**Comment by harshavardhana** [comment]
> Not really seeing any leak there.
> 
> Yes, the function could have pagination so a huge number of users don't take too much memory, but this is not really something that seems to worrysome.

Yeah this looks like normal and will be relinquished properly to Go runtime as needed.
