### ISSUE TITLE
AddUser support set policy name

### ISSUE THREAD

**Issue by cachalots** [minio/madmin-go#52]
The API is a supported and struct also declare policy name , but ```AddUser``` is not allowed to set.

**Comment by harshavardhana** [comment]
> The API is a supported and struct also declare policy name , but `AddUser` is not allowed to set.

You need to use after you create a user.

```
// SetPolicy - sets the policy for a user or a group.
func (adm *AdminClient) SetPolicy(ctx context.Context, policyName, entityName string, isGroup bool) error {
```
